### ISSUE TITLE
[1.7.10]: enableMixinWorldServer causing issues on modpacks 

### ISSUE THREAD

**Issue by quentin452** [quentin452/Multithreadingandtweaks#110]
### Modpack

Biggess Pack Cat Edition V0.96.6

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

logs : 
[net.minecraft.world.World:optimizationsAndTweaks$logExceptionDetails:51269]: (Optimizationsandtweaks logging)Exception getting block type in world at coordinates - x: 32, y: 64, z: -315
[06:07:19] [Server thread/INFO] [STDOUT/]: [net.minecraft.world.World:optimizationsAndTweaks$logExceptionDetails:51275]: (Optimizationsandtweaks logging)Exception details: java.lang.NullPointerException
[06:07:19] [Server thread/WARN] [ArchaicFix/]: Minecraft loaded a new chunk [7, -18] in dimension 1700 (Atum) while populating chunk [2, -20], causing cascading worldgen lag.
[06:07:19] [Server thread/WARN] [ArchaicFix/]: Stacktrace
java.lang.Exception: Cascading world generation
	at net.minecraft.world.chunk.Chunk.logCascadingWorldGeneration(Chunk.java:6652) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zoi000$archaicfix$savePopulatingChunk(Chunk.java:6658) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:51228) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:1624) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2786) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
[06:07:19] [Server thread/WARN] [ArchaicFix/]: Minecraft loaded a new chunk [6, -16] in dimension 1700 (Atum) while populating chunk [2, -20], causing cascading worldgen lag.
[06:07:19] [Server thread/WARN] [ArchaicFix/]: Stacktrace
java.lang.Exception: Cascading world generation
	at net.minecraft.world.chunk.Chunk.logCascadingWorldGeneration(Chunk.java:6652) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zoi000$archaicfix$savePopulatingChunk(Chunk.java:6658) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:51228) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:1624) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2786) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]

### Description

The bug is probably caused by a mod incompat

**Comment by quentin452** [comment]
Seem to be fixed by V1.13.2
