### ISSUE TITLE
incompat with better fps/ crash on startup

### ISSUE THREAD

**Issue by quentin452** [quentin452/Multithreadingandtweaks#2]
```
[08:48:12] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net.minecraft.block.BlockLiquid$Anonymous$34eae6448dee4fc1a6504b2671f329dd
	at net.minecraft.block.BlockLiquid.<clinit>(BlockLiquid.java:1148) ~[alw.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:212) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLiquid$Anonymous$34eae6448dee4fc1a6504b2671f329dd
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_362]
	at net.minecraft.block.BlockLiquid.<clinit>(BlockLiquid.java:1148) ~[alw.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:212) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at org.objectweb.asm.ClassReader.readShort(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:34) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at makamys.coretweaks.optimization.transformercache.lite.CachedTransformerProxy.transform(CachedTransformerProxy.java:25) ~[CoreTweaks-1.7.10-0.3.0.4+nomixin.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_362]
	at net.minecraft.block.BlockLiquid.<clinit>(BlockLiquid.java:1148) ~[alw.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:212) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 9 more
Exception caught from launcher
cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:389)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:389)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:76)
```

**Comment by quentin452** [comment]
better fps crash fixed duplicated #4
