### ISSUE TITLE
[1.7.10]: PRIVATE @Overwrite method func_75502_i in MixinPathNavigate cannot reduce visibiliy of PUBLIC target method

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#46]
### Modpack

Custom

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

https://pastebin.com/XJY83Kub

### Description

The game crashes when trying to launch from 1.2.1, if `B:enableMixinPathFinding=false`, then there is no crash

**Comment by Abalieno** [comment]
Without opening a new one, since it's somewhat related. The new problem is also about Ender IO.

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/pathfinding/PathNavigate
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4098)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/pathfinding/PathNavigate
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:3473)
    at java.lang.Class.getDeclaredField(Class.java:2780)
    at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:85)
    at crazypants.enderio.machine.spawner.BlockPoweredSpawner.<init>(BlockPoweredSpawner.java:112)
    at crazypants.enderio.machine.spawner.BlockPoweredSpawner.create(BlockPoweredSpawner.java:91)
    at crazypants.enderio.EnderIO.preInit(EnderIO.java:429)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.pathfinding.PathNavigate
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:224)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 43 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
    at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:367)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:198)
    ... 45 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.optimizationsandtweaks.json:common.core.pathfinding.MixinPathNavigate from mod optimizationsandtweaks] from phase [DEFAULT] in config [mixins.optimizationsandtweaks.json] FAILED during APPLY
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
    ... 50 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_75502_i in mixins.optimizationsandtweaks.json:common.core.pathfinding.MixinPathNavigate from mod optimizationsandtweaks cannot reduce visibiliy of PUBLIC target method
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479)
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452)
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416)
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346)
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
    at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    ... 50 more

        net.minecraft.pathfinding.PathNavigate:
            org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_75502_i in mixins.optimizationsandtweaks.json:common.core.pathfinding.MixinPathNavigate from mod optimizationsandtweaks cannot reduce visibiliy of PUBLIC target method
    Mixins in Stacktrace: 
        net.minecraft.pathfinding.PathNavigate:
            mixins.optimizationsandtweaks.json:common.core.pathfinding.MixinPathNavigate from mod optimizationsandtweaks
        net.minecraft.client.Minecraft:
            mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes
            mixins.hodgepodge.early.json:minecraft.profiler.MinecraftMixin from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UpdateKeys from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ToggleDebugMessage from mod hodgepodge
            mixins.archaicfix.early.json:client.core.MixinMinecraft from mod archaicfix
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ResizableFullscreen from mod hodgepodge
            mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UnfocusedFullscreen from mod hodgepodge
            mixins.archaicfix.early.json:client.lighting.MixinMinecraft from mod archaicfix
        crazypants.enderio.machine.spawner.BlockPoweredSpawner:
            mixins.mobsinfo.json:EnderIO.BlockPoweredSpawnerAccessor from mod mobsinfo
        cpw.mods.fml.client.FMLClientHandler:
            coretweaks-preinit.mixin.json:optimization.fmlmessagestrip.MixinFMLClientHandler from mod (unknown)
            mixins.archaicfix.early.json:client.core.MixinFMLClientHandler from mod archaicfix
        cpw.mods.fml.common.LoadController:
            mixin.mixinbooterlegacy.json:LoadControllerMixin from mod (unknown)
    Suspected Mods: Ender IO (EnderIO)

**Comment by quentin452** [comment]
This version should fix #47 #46 :  https://mega.nz/file/motXkYxb#V0dyLn7NtegH5BZOjP1UydCDliP0QalSq47EfoFIKjQ
