### ISSUE TITLE
[1.7.10]: 

### ISSUE THREAD

**Issue by zeff9801** [quentin452/Multithreadingandtweaks#52]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(NibbleArray.java:542)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76670_c(ExtendedBlockStorage.java:156)
	at net.minecraft.world.chunk.Chunk.func_76614_a(Chunk.java:770)
	at net.minecraft.world.World.func_72972_b(World.java:5330)
	at net.minecraft.world.World.updateLightByType(World.java:3782)
	at net.minecraft.world.World.func_147463_c(World.java:4930)
	at net.minecraft.world.World.func_147451_t(World.java:3708)
	at net.minecraft.world.World.func_72903_x(World.java:5454)
	at net.minecraft.world.World.func_147456_g(World.java:3595)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:444)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Thread.java:748)

### Description

Crash during chunks exploring probably related to one of the mixins

**Comment by quentin452** [comment]
Can you try disabling enableMixinNibbleArray

If the issue diseappar with enableMixinNibbleArray disabled , try reenabling it and using this dev build
(don't unzip the zip)
[optimizationsandtweaks-V1.2.8-1-7-10.3+575e4f5bd5-dirty.zip](https://github.com/quentin452/OptimizationsAndTweaks/files/13221805/optimizationsandtweaks-V1.2.8-1-7-10.3%2B575e4f5bd5-dirty.zip)

if the issue appear again with enableMixinNibbleArray disabled give to me the new log

**Comment by zeff9801** [comment]
I can confirm the dev version seems to have fixed the issue and the server nolonger crashes with it enabled
